spring:
  application:
    name: exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      nbpApiCircuitBreaker:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 60
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      geoLocationServiceRetry:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 1.5
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException


currency:
  api:
    nbp:
      url: "https://api.nbp.pl/api/exchangerates/rates/a/{currency}/?format=json"

jwt:
  secret:
    key: 0secret034n35h45jj345nkj3794gfrhfbjkdf83725
